apiVersion: v1
kind: Service
metadata:
  name: node-hello-svc
### updated with annotation
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: node-hello
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP

